# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfe894d6c22e002a7884de30d64bacd47cd8d8f6ab6ba2b52a3c347ea1226ab43f08eb278840f21134c5d77ecb3f46fa94e27732c914543a892712d21aa5781b

test:
  secret_key_base: c301850317646ca3153ac31009fd2969366809a6af2d698d41f62402d5fda13656526e65b51e9706749ee1931e68eb89134b20438c0b54086b3bcbae52b0a270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
